[project]
name = 'supply-chain-transparency-tracker'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.product-lifecycle-tracker]
path = 'contracts/product-lifecycle-tracker.clar'
clarity_version = 2
epoch = 2.5

[contracts.verification-badge-system]
path = 'contracts/verification-badge-system.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
